# Generated by Django 4.2.5 on 2024-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_to_name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
