# Generated by Django 4.2.5 on 2024-01-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_alter_invoice_bill_to_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bill_to_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bill_to_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
